---
- name: Download WordPress
  get_url:
    url: https://fr.wordpress.org/wordpress-6.3.1-fr_FR.tar.gz
    dest: /srv/wordpress-6.3.1-fr_FR.tar.gz

- name: Extract archive
  unarchive:
    creates: /srv/wordpress
    src: /srv/wordpress-6.3.1-fr_FR.tar.gz
    dest: /srv/

- name: Add group "wordpress"
  group: name=wordpress

- name: Add user "wordpress"
  user:
    name: wordpress
    group: wordpress
    home: /srv/wordpress/

- name: Create WordPress database
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present

- name: Fetch random salts for WordPress config
  get_url:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    dest: /srv/wordpress/
  register: wp_salt

- name: Create WordPress database user
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: 'localhost'
    state: present

- name: Copy WordPress config file
  template:
    src: wp-config.php
    dest: /srv/wordpress/

- name: Change ownership of WordPress installation
  file:
    path: /srv/wordpress/
    owner: wordpress
    group: wordpress
    state: directory
    recurse: yes

- name: Start php-fpm Service
  service:
    name: php8.2-fpm
    state: started
    enabled: yes

